schema_class LiveryCompanies::Schema

<connect_info>
  dsn	dbi:SQLite:dbname=db/livery.db
  user	''
  password	''

  <options>
    sqlite_unicode 1
    quote_names 1
    RaiseError 1
    PrintError 0
    AutoCommit 1
  </options>
</connect_info>

<loader_options>
  dump_directory lib
  naming v8
  components	InflateColumn::DateTime
  components	TimeStamp
  use_namespaces 1
  use_moose 1
</loader_options>
